# Generated by Django 2.2.17 on 2021-01-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_hgjgfhj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hgjgfhj',
        ),
    ]
